version: '2'

services:
  rabbit:
    image: rabbitmq:3
    container_name: taiga_rabbit
    networks:
      - back-tier
    environment:
      RABBITMQ_DEFAULT_VHOST: taiga

  redis:
    image: redis:3
    container_name: taiga_redis
    networks:
      - back-tier

  postgres:
    image: postgres
    hostname: postgres
    container_name: taiga_postgres
    environment:
      POSTGRES_DB: ${TAIGA_DB_NAME}
      POSTGRES_USER: ${TAIGA_DB_USER}
      POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
    # ports:
    #   - 5432:5432
    networks:
      - back-tier
    # volumes:
      # - "${PWD}/database:/var/lib/postgresql/data"
      # - postgres-data

  docker_mail_server:
    image: juanluisbaptiste/postfix
    container_name: docker_mail_server
    networks:
      - back-tier
    ports:
      - ${EMAIL_PORT}:25
    environment:
      SMTP_SERVER: ${EMAIL_HOST}
      SMTP_USERNAME: ${EMAIL_HOST_USER}
      SMTP_PASSWORD: ${EMAIL_HOST_PASSWORD}

  celery:
    image: celery
    networks:
      - back-tier
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis"

  taiga-events:
    build: docker-taiga-events
    image: taiga-events
    container_name: taiga_events
    networks:
      - back-tier
    depends_on:
      - rabbit
  
  taiga:
    build: .
    container_name: taiga
    image: taiga
    ports:
      - "${TAIGA_PORT}:80"
      # - 443:443 # To enable SSL, uncomment this line
    networks:
      - front-tier
      - back-tier
    depends_on:
      - postgres
      - rabbit
      - redis
      - celery
      - taiga-events
    environment:
      TAIGA_HOSTNAME: "${TAIGA_HOST}:${TAIGA_PORT}"
      # TAIGA_SLEEP haults Taiga from starting for 30 seconds,
      # this gives the database container time to initialize.
      # If you're using an external database you can remove this.
      TAIGA_SLEEP: 10
      # TAIGA_SSL=True # To enable SSL, uncomment this line
      
      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: ${TAIGA_DB_NAME}
      TAIGA_DB_USER: ${TAIGA_DB_USER}
      TAIGA_DB_PASSWORD: ${TAIGA_DB_PASSWORD}

      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

      GITHUB_URL: "https://github.com/"
      GITHUB_API_URL: "https://api.github.com/"
      GITHUB_API_CLIENT_ID: "yourgithubclientid"
      GITHUB_API_CLIENT_SECRET: "yourgithubclientsecret"
    # volumes:
      # This ensures files uploaded to Taiga are not lost when recreating
      # your taiga container during upgrades
      # - "${PWD}/media:/usr/src/taiga-back/media"

# volumes:
#   postgres-data:
#     driver: local

networks:
  front-tier:
  back-tier:
